creds:
    email: me@gmail.com
    user: me
    password: password
    sleep_time: 5
    owner: owner@gmail.com
white_list:
    bro@gmail.com, sis@gmail.com
pin:
    2
mongodb:
    url: ''
    user: user
    password: password
    db_name: generator